networks:

  jellyfinnetwork:
    name: jellyfinnetwork
    ipam:
      config:
        - subnet: 172.41.0.0/24
        
services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - ./jellyfin/.env
    volumes:
      - ./jellyfin:/config
      - /data:/data
    devices:
      - /dev/dri:/dev/dri #Use for Intel QuickSync
    ports:
      - 8096:8096
      - 7359:7359/udp #Service Discovery
      - 1900:1900/udp #Client Discovery
    restart: unless-stopped
    networks:
      jellyfinnetwork:
        ipv4_address: 172.41.0.2
    labels:
      - "com.centurylinklabs.watchtower.scope=jellyfin-service"

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    env_file:
      - ./jellyseerr/.env
    volumes:
      - ./jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      jellyfinnetwork:
        ipv4_address: 172.41.0.3
    labels:
      - "com.centurylinklabs.watchtower.scope=jellyfin-service"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: jellyfin-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --interval 300
      --cleanup
      --scope jellyfin-service
    restart: always
    networks:
      jellyfinnetwork:
        ipv4_address: 172.41.0.4

# Want more!? https://github.com/awesome-jellyfin/awesome-jellyfin
